# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AII Informatica Essentials
email: ha.meijer@avans.nl
description: >- # this means to ignore newlines until "baseurl:"
  Regelmatig is er discussie over de manier waarop concepten, theorieën of paradigma's aan studenten uitgelegd moeten worden.
  Het doel van deze repository is om overeenstemming te krijgen tussen docenten over de definitie die wij onze studenten willen aanleren. Het resultaat zou moeten zijn dat verschillende docenten in hun theorie, tijdens de lessen en beoordelingen consistenter zijn.
baseurl: "/AII-Informatica-Essentials" # the subpath of your site, e.g. /blog
url: "https://avans.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rikmeijer
destination: ./docs

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - AII-Informatica-Essentials.iml